### ISSUE TITLE
Fails on start

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [equinusocio/hyper-material-theme#1]
Installing this theme without special attention leads to Hyper failingh with:

```
Uncaught Exception:
TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.exports.decorateConfig (~/.hyper_plugins/node_modules/hyper-material-theme/index.js:94:20)
    at modules.forEach.plugin (/Applications/Hyper.app/Contents/Resources/app/plugins.js:330:30)
    at Array.forEach (native)
    at decorateObject (/Applications/Hyper.app/Contents/Resources/app/plugins.js:328:11)
    at Object.exports.getDecoratedConfig (/Applications/Hyper.app/Contents/Resources/app/plugins.js:352:10)
    at install (/Applications/Hyper.app/Contents/Resources/app/plugins.js:226:50)
    at updatePlugins (/Applications/Hyper.app/Contents/Resources/app/plugins.js:76:3)
    at Timeout.setTimeout (/Applications/Hyper.app/Contents/Resources/app/plugins.js:170:5)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

The reason is that your configuration options such as ```theme``` or ```backgroundOpacity``` are not set by default.

**Comment by equinusocio** [comment]
You know how to fix this?

**Comment by equinusocio** [comment]
@MatthiasWinkelmann You can fix this by adding
```
theme: `${ config.theme || '' }`,
```
inside the `object.assing()`
