### ISSUE TITLE
Plugin load error: "hyper-material-theme" failed to load in the renderer process

### ISSUE THREAD

**Issue by adeonir** [equinusocio/hyper-material-theme#16]
I just installed Hyper in Windows 10 with Chocolatey and after adding the theme in hyper.js, I got this error.

```js
Error: Cannot find module 'undefined/.hyper.js'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\adeonir\AppData\Local\hyper\app-1.3.3\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\adeonir\.hyper_plugins\node_modules\hyper-material-theme\index.js:2:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by equinusocio** [comment]
Seems that `process.env.HOME + '/.hyper.js'` doesn't work on windows..

**Comment by adeonir** [comment]
@equinusocio I had to manually add an environment variable with `HOME` set for my user folder. Now it works.

**Comment by equinusocio** [comment]
I hate windows..

**Comment by ImJoeHs** [comment]
Same problem, `HOME` in windows is `HOMEPATH`..

**Comment by ImJoeHs** [comment]
Oh, I just found the latest commit . Never mind.

**Comment by equinusocio** [comment]
@ImJoeHs 2.0.1 works?

**Comment by ImJoeHs** [comment]
@equinusocio Sry I got some jobs. 
Yes it works~ Thanks!

**Comment by adeonir** [comment]
@equinusocio I hate windows too. I use at work, so I do not have much to do ...
Thanks, now it works!
