### ISSUE TITLE
Material theme causes Hyper to stop working

### ISSUE THREAD

**Issue by nonsocode** [equinusocio/hyper-material-theme#20]
Whenever i enable material theme and reload, the terminal stops working. All i get is the background of the terminal. When i close hyper and open it again, the GUI never loads. It shows up on my list of running processes but there is no GUI.

This is the error from the console
```
C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\renderer\api\remote.js:217 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'theme' of undefined
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'theme' of undefined
    at callFunction (C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\browser\rpc-server.js:235:11)
    at EventEmitter.<anonymous> (C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\browser\rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\browser\api\web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)metaToValue @ C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\renderer\api\remote.js:217(anonymous function) @ bundle.js:47__webpack_require__ @ bundle.js:1(anonymous function) @ bundle.js:1(anonymous function) @ bundle.js:1
index.html:35 total init time 485.75
```

**Comment by equinusocio** [comment]
#19
