### ISSUE TITLE
plugin prevent Hyper to load 

### ISSUE THREAD

**Issue by hyphaene** [equinusocio/hyper-material-theme#23]
Hi, 

I'm on Ubuntu 16.04

I have an issue when I add the plugin on the array of plugins : 
( printed when I run hyper from the terminal )

```
running in prod mode
electron will open file:///opt/Hyper/resources/app/index.html
Error while loading devtools extensions TypeError: Cannot read property 'theme'of undefined
    at Object.exports.decorateConfig.config [as decorateConfig] (/home/personne/.hyper_plugins/node_modules/hyper-material-theme/index.js:17:18)
    at modules.forEach.plugin (/opt/Hyper/resources/app/plugins.js:345:30)
    at Array.forEach (native)
    at decorateObject (/opt/Hyper/resources/app/plugins.js:343:11)
    at Object.exports.getDecoratedConfig (/opt/Hyper/resources/app/plugins.js:367:10)
    at createWindow (/opt/Hyper/resources/app/index.js:107:23)
    at installDevExtensions.then (/opt/Hyper/resources/app/index.js:379:3)
```
I've manually installed the package inside the `~/.hyper_plugins` directory to ensure it was installed.

Cheers

**Comment by equinusocio** [comment]
#19
